// Copyright © 2019-2023
// Licensed under the Apache License, Version 2.0
// Translated from VX_uop_sequencer.sv

package vortex

import chisel3._
import chisel3.util._

import VortexGPUPkg._
import VortexConfigConstants._
import TcuPkg._

/** VX_uop_sequencer: micro-op sequencer for multi-cycle instructions.
 *
 *  When EXT_TCU_ENABLE is set and the incoming instruction is a WMMA op, the
 *  sequencer holds the instruction buffer and drives a sequence of micro-ops
 *  generated by VX_tcu_uops.  For all other instructions (or when TCU is not
 *  enabled) the module is a transparent pipe.
 *
 *  The current configuration has EXT_TCU_ENABLED = 0, so the unit degenerates
 *  to a wire-through (is_uop_input = 0, uop_active never set).  A future
 *  TCU-enabled build would need to instantiate VxTcuUops here.
 *
 *  Port names follow the flat convention:
 *    input_if  → {input_valid, input_ready, input_data}
 *    output_if → {output_valid, output_ready, output_data}
 *  where "data" is the packed ibuffer_t bit-vector.
 */
class VxUopSequencer extends Module {
  import VortexGPUPkg._
  import VortexConfigConstants._

  // ibuffer_t width
  private val ibufDataW = UUID_WIDTH + ISSUE_WIS_W + NUM_THREADS + PC_BITS +
                          EX_BITS + INST_OP_BITS + INST_ARGS_BITS +
                          1 + NUM_SRC_OPDS + NUM_REGS_BITS * 4

  val io = IO(new Bundle {
    // Slave: instruction buffer output
    val input_valid = Input(Bool())
    val input_ready = Output(Bool())
    val input_data  = Input(UInt(ibufDataW.W))

    // Master: sequenced (possibly expanded) instruction stream
    val output_valid = Output(Bool())
    val output_ready = Input(Bool())
    val output_data  = Output(UInt(ibufDataW.W))
  })

  // -------------------------------------------------------------------------
  // EXT_TCU_ENABLED == 0 path (default configuration)
  //
  // is_uop_input = 0
  // uop_done     = 0 (uop_data unused)
  // uop_active   never set → stays 0
  //
  // Transparent pipe:
  //   output_valid = input_valid
  //   output_data  = input_data
  //   input_ready  = output_ready
  // -------------------------------------------------------------------------

  if (EXT_TCU_ENABLED == 0) {
    // No TCU: sequencer is a straight wire
    io.output_valid := io.input_valid
    io.output_data  := io.input_data
    io.input_ready  := io.output_ready

  } else {
    // -----------------------------------------------------------------------
    // EXT_TCU_ENABLED == 1 path
    //
    // is_uop_input: check ex_type == EX_TCU && op_type == INST_TCU_WMMA
    // (exact field offsets within ibuf_data depend on packing convention;
    //  matched to VortexGPUPkg ibuffer_t layout: eop|sop|rs3|rs2|rs1|rd|used_rs|wb|op_args|op_type|ex_type|PC|tmask|wis|uuid)
    //
    // Because EXT_TCU_ENABLED is 0 in this codebase the branch below is dead
    // but is included for completeness / future enablement.
    // -----------------------------------------------------------------------

    // Extract ex_type and op_type from the data word.
    // Layout (LSB=0): uuid[UUID_WIDTH-1:0] | wis[ISSUE_WIS_W] | tmask[NUM_THREADS] |
    //                 PC[PC_BITS] | ex_type[EX_BITS] | op_type[INST_OP_BITS] | ...
    val exTypeOff = UUID_WIDTH + ISSUE_WIS_W + NUM_THREADS + PC_BITS
    val opTypeOff = exTypeOff + EX_BITS
    val exTypeF   = io.input_data(exTypeOff + EX_BITS - 1, exTypeOff)
    val opTypeF   = io.input_data(opTypeOff + INST_OP_BITS - 1, opTypeOff)

    val isUopInput = (exTypeF === EX_TCU.U) && (opTypeF === INST_TCU_WMMA.U)

    // TCU uop engine (stub; VxTcuUops not yet translated)
    val tcuUops = Module(new VxTcuUopsBB(ibufDataW))
    tcuUops.io.ibuf_in := io.input_data
    tcuUops.io.start   := io.input_valid && isUopInput
    tcuUops.io.next    := io.output_ready
    val uopData = tcuUops.io.ibuf_out
    val uopDone = tcuUops.io.done

    val uopActive = RegInit(false.B)
    when (uopActive) {
      when (io.output_ready && uopDone) {
        uopActive := false.B
      }
    }.otherwise {
      when (io.input_valid && isUopInput) {
        uopActive := true.B
      }
    }

    val uopHold = !uopActive && isUopInput

    io.output_valid := Mux(uopActive, true.B, io.input_valid && !uopHold)
    io.output_data  := Mux(uopActive, uopData, io.input_data)
    io.input_ready  := Mux(uopActive,
                           io.output_ready && uopDone,
                           io.output_ready && !uopHold)
  }
}

/** BlackBox stub for VX_tcu_uops (only needed when EXT_TCU_ENABLED = 1). */
class VxTcuUopsBB(ibufDataW: Int) extends Module {
  val io = IO(new Bundle {
    val ibuf_in  = Input(UInt(ibufDataW.W))
    val ibuf_out = Output(UInt(ibufDataW.W))
    val start    = Input(Bool())
    val next     = Input(Bool())
    val done     = Output(Bool())
  })
  io.ibuf_out := 0.U
  io.done     := false.B
}
